### ISSUE TITLE
Generated key not sliced to appropriate length

### ISSUE THREAD

**Issue by kaikuchn** [rosenfeld/rails_compatible_cookies_utils#1]
Edit: Since Rails apparently generates keys longer than the 32 bytes that are required and then when it uses them [cuts them to the appropriate length](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/cookies.rb#L579), we will need to do the same.

Below is my initial issue report.

Hi there,

first off thank you very much for providing this gem! It's been a life saver for me!
With the advent of Ruby 2.4 there seems to have been a change within Ruby's `OpenSSL::Cipher` class which makes it more picky about key sizes revealing that the defaults of `RailsCompatibleCookiesUtils#initialize` are not compatible.

The specified cipher is 'aes-256-cbc' which results in a key length of 32, default `key_size` is however 64.

The error that users will encounter is:
```shell
ArgumentError: key must be 32 bytes
    [...]/bundle/gems/rails_compatible_cookies_utils-0.1.0/lib/rails_compatible_cookies_utils.rb:47:in `key='
    [...]/bundle/gems/rails_compatible_cookies_utils-0.1.0/lib/rails_compatible_cookies_utils.rb:47:in `decrypt'
```

Specifying the correct `key_size` when initializing the `RailsCompatibleCookiesUtils` will prevent the error, but decryption now failes which leads me to suspect that the old behaviour of `OpenSSL::Cipher` was to just ignore the remaining bytes and now the key generation is fucked up.

A quick hack to [rails_compatible_cookies_utils.rb:47](https://github.com/rosenfeld/rails_compatible_cookies_utils/blob/master/lib/rails_compatible_cookies_utils.rb#L47) to use only the first 32 bytes of the `encrypted_secret` which was generated to have 64 bytes supports this hypothesis.

**Comment by kaikuchn** [comment]
Also see [here](https://bugs.ruby-lang.org/issues/12561) for the issue that prompted this particular change to `OpenSSL::Cipher`

**Comment by rosenfeld** [comment]
I've been working like crazy in the past few months due to some atypical demand and since I have to little girls to take care of, I don't have any time off work... Due to all this demand I didn't have time to upgrade to 2.4 yet, but after you reported this issue, I just did it and I can confirm the failing specs due to "key must be 32 bytes". I'll look at your investigation and will try to fix that problem as soon as possible without breaking backwards compatibility... Thanks for your detailed report and investigation.

**Comment by rosenfeld** [comment]
Try upgrading to 0.1.1 and please let me know if you find any issues with it.

**Comment by rosenfeld** [comment]
Or if you need to configure another cipher that not the default one, you should upgrade to 0.1.2.

**Comment by kaikuchn** [comment]
Wow, thank you for this super fast response! 0.1.1 works! Thank you so much!
I'm happy to have been of help!

Also, please enjoy your time off work with your girls! No reason to apologise for that!

**Comment by rosenfeld** [comment]
I wasn't really apologizing, just explaining why it's taking a while for me to update my gems to keep them up-to-date as it's usually the case ;) Also, when I find some little time after work I usually take the chance to practice mandolin rather than working on OSS :)

**Comment by kaikuchn** [comment]
👍  Thank you again, have a nice day!

**Comment by rosenfeld** [comment]
Thanks, you too.
